import { getFileName } from "./pathUtils";

interface ExportData {
  repoInfo: { owner: string; repo: string };
  overview: {
    summary: string;
    techStack: string[];
    startHere: { path: string; reason: string }[];
  };
  files: { path: string; type: string }[];
}

function groupFilesByFolder(
  files: { path: string; type: string }[],
): Map<string, string[]> {
  const map = new Map<string, string[]>();
  files
    .filter((f) => f.type === "blob")
    .forEach((f) => {
      const segments = f.path.split("/");
      const folder =
        segments.length > 1 ? segments.slice(0, -1).join("/") + "/" : "(root)";
      if (!map.has(folder)) map.set(folder, []);
      map.get(folder)!.push(getFileName(f.path));
    });
  return map;
}

export function buildMarkdown(data: ExportData): string {
  const { repoInfo, overview, files } = data;
  const lines: string[] = [];

  lines.push(`# ${repoInfo.owner}/${repoInfo.repo} — Repository Analysis`);
  lines.push("");
  lines.push(
    "> Generated by **Tracepaper** — AI-powered GitHub repo onboarding",
  );
  lines.push("");
  lines.push("## Overview");
  lines.push("");
  lines.push(overview.summary);
  lines.push("");

  if (overview.techStack.length > 0) {
    lines.push(`**Tech stack:** ${overview.techStack.join(", ")}`);
    lines.push("");
  }

  if (overview.startHere.length > 0) {
    lines.push("## Recommended Reading Order");
    lines.push("");
    overview.startHere.forEach((f, i) => {
      lines.push(`${i + 1}. \`${f.path}\` — ${f.reason}`);
    });
    lines.push("");
  }

  lines.push("## File Structure");
  lines.push("");
  const grouped = groupFilesByFolder(files);
  const sortedFolders = Array.from(grouped.keys()).sort();
  sortedFolders.forEach((folder) => {
    lines.push(`### ${folder}`);
    lines.push("");
    grouped
      .get(folder)!
      .sort()
      .forEach((name) => {
        lines.push(`- ${name}`);
      });
    lines.push("");
  });

  lines.push("---");
  lines.push("");
  lines.push(
    "_This document was auto-generated and may not capture every nuance of the codebase. Use it as a starting point, not a substitute for reading the code._",
  );

  return lines.join("\n");
}

export function downloadMarkdown(filename: string, content: string): void {
  const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
